repos:
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3.8
  - repo: local
    hooks:
      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: system
        types: [python]
        args: [--py37-plus]

      - id: django-test
        name: django-test
        entry: pytest src/
        always_run: true
        pass_filenames: false
        language: system

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8

